### ISSUE TITLE
No Fan available

### ISSUE THREAD

**Issue by marrocc** [Robbe-B/maestro_mcz#101]
After update 0.5.0 all fans are no longer available. Previously only fan 1 was not available. I have an MCZ Musa comfort air with front fan and two other rear duct fans.

**Comment by Robbe-B** [comment]
Can you provide me with diagnostics file ?

**Comment by Robbe-B** [comment]
@marrocc,
What do you mean with no longer available ? 
Can you please provide me with a screenshot ? 
Fans will be like this, if the current mode doesn't support fan control: 
![image](https://github.com/Robbe-B/maestro_mcz/assets/103053873/2c1bedc2-e04f-42dc-983a-2aee8b1e7b30)

**Comment by marrocc** [comment]
> Hi @marrocc, Can you provide me with diagnostics file ? Kind regards, Robbe

[config_entry-maestro_mcz-b6df10573a15b49bc97a3ec74e22e430.json.txt](https://github.com/Robbe-B/maestro_mcz/files/13979074/config_entry-maestro_mcz-b6df10573a15b49bc97a3ec74e22e430.json.txt)

**Comment by Robbe-B** [comment]
@marrocc, 
In the diagnostics file, I see your stove is in comfort mode.
This mode doesn't allow fan control, it's the same in the MCZ app.
When changing your stove to another mode (e.g. Auto) the fans will become available again.

Also, if you like the work we do, consider leaving a star on this repo.
Thanks !

Kind regards,
Robbe

**Comment by marrocc** [comment]
Thanks a lo for your good job.  Howewer i prefer to see the fans available in every mode settings like previous versione. In the comfort mode, the stove don't allow the fans control but the fans are present and works. If i create a card in home assistant, i would like to see the fans entity in confort mode too.
Kind regards.  
Pasquale.

**Comment by Robbe-B** [comment]
@marrocc,
Unfortunately, we can not do this for multiple reasons. 

First, fan control is now coupled to the configuration of the current mode in orde to fix alot of bugs with these fans. The main reason MCZ removed the 1st fan to be controlled seperatly. Was probably in order to force us to use the correct config for the current mode.

Second, we don't want to provide any actions that you can not do on the stove anyway. For multiple safety reasons. We want to keep within the scenario that MZC tested. Otherwise if this stove burns your house down in a configuration that wasn't allowed in the first place. Who is responsible for this ? 

I hope you see we try to respect certain bounderies here.

Kind regards,
Robbe
