### ISSUE TITLE
Plus d'entitée climat depuis la version 5.0

### ISSUE THREAD

**Issue by CarpeDiem40** [Robbe-B/maestro_mcz#129]
**Describe the bug**

**Expected behavior**

**Screenshots**

**Diagnostics File**
While the bug is present, download the diagnostics file and attach it to this report.

**Comment by Robbe-B** [comment]
@CarpeDiem40, 
Thanks for reporting, can you attach your diagnostics file please ? 
This can be found here => 
![image](https://github.com/Robbe-B/maestro_mcz/assets/103053873/6f8c17a0-93a5-4a19-b783-a83ba9c59d73)

**Comment by Robbe-B** [comment]
@CarpeDiem40, 
You have any update with this file for me ? 
Kind regards,
Robbe

**Comment by Robbe-B** [comment]
@CarpeDiem40, 
I'll close this one, since this is probably the same as => https://github.com/Robbe-B/maestro_mcz/issues/106
Try to upgrade your Home Assistant to the latest version.
If this doesn't help, completely remove this integration and try to re-install this integration.
If all this, if the issue is still present, leave a comment here with your diagnostics file.
