### ISSUE TITLE
Problem with touch buttons

### ISSUE THREAD

**Issue by Leon3310** [Robbe-B/maestro_mcz#136]
Good evening,

I've had a problem with my pellet stove since the end of March. It's certainly not related to the home assistant integration but maybe someone can help me. My warranty expired in February (2 years) ;(

Here is my problem:

The touch buttons on my stove no longer work. The screen still displays information. The only way I have left to operate my stove is with the Maestro+ app and Home assistant ;)

**Comment by Robbe-B** [comment]
Did you tried a factory reset of the stove ?
If this display is a collapsible one, it might be a bad wire in the cable. (caused by many collapse actions of this display)
I would recommend checking the connection of that cable to the main board in the stove.
I'm also not sure, but I believe replacing this part is possible since it's just a separate module plugged in on the main board.
Kind regards

**Comment by Robbe-B** [comment]
@Leon3310, 
Do you have any update on this is the meanwhile ?

**Comment by Leon3310** [comment]
Hello,
I had to ask a technician to come.  He had to replace the control panel. It cost me 280€ + the maintenance of my stove... (it cost me more than a year's heating)...
He told me that this happens from time to time, but often when the stove is being installed.

I'm still going to send an e-mail to MCZ

**Comment by Robbe-B** [comment]
@Leon3310, 
Did you got any response from MCZ on your email ?

**Comment by Leon3310** [comment]
I didn't send an e-mail...
