### ISSUE TITLE
Automatic update is not working.

### ISSUE THREAD

**Issue by pvillmann** [Robbe-B/maestro_mcz#156]
Hi,

First of all many thanks for creating this integration.
I've installed my MCZ Club Hydromatic in 2020 with the idea "hey this stove has WiFi, I will find a way to integrate in HA or similar." After 3 years I found this integration and with that the first working solution.

Now my problem: sometimes the data shown in HA is not up to date.
Solution:
I start the iOS App and wait a few seconds until the data in the app is the same like directly at the stove. After that the HA data change with next refresh and everything is fine.

**Comment by Robbe-B** [comment]
Hi @pvillmann,
It's great to hear that this integration finally closes the gap between MCZ and HA for you ! 
The issue that you are describing here is not unknow to us, for some older models we are aware this is happening.
See https://github.com/Robbe-B/maestro_mcz/issues/114 , which is the same issue.
The reason this is not fixed yet, is simply because we don't have access to older stove models. 
That's why we are asking folks to maybe give us access to their stoves in order to figure out how this actually works.
@Crisicus is the expert in finding these things out tbh.
I'll close this issue in favour of the other one, you can follow up on that one.
Kind regards,
Robbe
