### ISSUE TITLE
Values not being polled by themselves anymore. 

### ISSUE THREAD

**Issue by htbuddha** [Robbe-B/maestro_mcz#162]
**Describe the bug**
The values, amongst which the ambient temperature (sensor.1911140050034_ambient_temperature) do not update anymore on its own. They only update when I open the MCZ app on my phone.
I'm not sure, but I THINK this issue arose since some HA update.

**Expected behavior**
The values should update every X seconds based on the "interval to poll data" setting, which is the default 30 seconds in my HA. 

**Screenshots**
![image](https://github.com/user-attachments/assets/cd692665-87cf-4184-a032-6d679da6708e)

**Diagnostics File**
Please tell me which file(s) I should upload, where I can find them... for you to debug this.

**Comment by htbuddha** [comment]
Looks like it might be related to the MCZ Maestro - Upgrade app (?)
It often does not update the values (20.5 celsius on the stove, 22 celsius still on the app). 

https://apps.apple.com/be/app/mcz-maestro-upgrade/id6450749440?l=nl

There was an update 1 month ago. to Version 1.7.3. I'd like to roll back to 1.7.2. to see if the issue is resolved then, but I'm not sure how to get the 1.7.2. version on my phone.

**Comment by htbuddha** [comment]
It looks very similar indeed, though I have not had this issue since February. This is a very recent appearance for me. Either since last HA updates or MCZ - Upgrade App update. I'd say the issue has been happing for maybe a month now. 

Very annoying as I rely greatly on this. 

HA does not get the data anymore, unless I open the app on my phone. (Either apps, the non upgrade app, with flames in the icon or the upgrade app)

**Comment by htbuddha** [comment]
Another weird thing is that this morning my automation was actually successfully triggered. Since this issue arose it hasn't been triggered lately. 

![image](https://github.com/user-attachments/assets/301f46fc-d20e-43a0-b24c-d83078dc9f0a)

![image](https://github.com/user-attachments/assets/2af5f690-f310-4807-ae72-81f11b014710)
![image](https://github.com/user-attachments/assets/52ae15a7-4d0b-4edd-adce-bb851ed29d06)


As you can see the graph in picture one does not reflect the change in temperate correctly.

**Comment by Robbe-B** [comment]
@htbuddha,
In order to start somewhere, can you give me the diagnostics file ?

**Comment by htbuddha** [comment]
Sure how can I send it privately? Do you have discord?

**Comment by Robbe-B** [comment]
@htbuddha, 
All security critical fields are already redacted by the integration.
You can safely post it here.

**Comment by htbuddha** [comment]
I'm hesitant because it displays which devices are present in my household. I'm a security oriented person. 

Here, it will be burned after reading once: https://brnaftr.me/bxrqKEzd4H/habiTant-Produce-eLigible-skEtch

**Comment by Robbe-B** [comment]
@htbuddha, 
Since when did this stopped working ? 
Can you see this in your HA history ? 
Kind regards,
Robbe

**Comment by htbuddha** [comment]
I'm restoring to a 6 October backup of HA, will report back.

**Comment by htbuddha** [comment]
Appears to have the same issue on the following HA version: 
![image](https://github.com/user-attachments/assets/3f9813b2-3451-4527-85bd-22059581d1ec)

Odds are its the 1.7.3 "MCZ - Upgrade" app update, how would I go about obtaining version 1.7.2 .ipa to side load?

**Comment by Robbe-B** [comment]
> Odds are its the 1.7.3 "MCZ - Upgrade" app update, how would I go about obtaining version 1.7.2 .ipa to side load?

I'm not sure what you mean by this, because the android/iOS app doesn't have anything to do with this integration.
MCZ frequently updates there backend (cloud) servers, here they often make changes that then goes hand in hand with an android/iOS app update.
Our goal here is to mimic the behavior of this app into a home assistant integration, making it a challenge for us to keep up.

The only things that might have introduced this issue are the following:
1. MCZ Cloud Server logic update => We need to counter this by finding out what they've changed.
2. A MCZ Integration for Home Assistant change (this repo) => I did something wrong in the code, introducing this issue.
3. A HA Core update (very unlikely) => Some changes in the core HA repo introduced this issue.
4. A MCZ Stove Firmware update got installed, introducing this issue (unlikely because I would then expect this same issue in the Android /iOS app)

I suspect it will be the first one, it's out of our control, MCZ doesn't really have a public API, nor do they have documentation for us to use on this.

**Comment by htbuddha** [comment]
I think the app does actually have something to do with this. 
The previous versions of the MCZ stoves have two apps available. 

This app - The "dumb" app:
https://play.google.com/store/apps/details?id=it.fluidsoft.mcz.maestro&hl=nl
And this app - the "upgrade" app:
https://play.google.com/store/apps/details?id=it.mcz.maestro.one&hl=nl

In order for my stove to be connected with the cloud, I had to install the "upgrade" app. And it is only with the upgrade app, that this integration works. I believe the upgrade app reads the values from the stove locally, and pushes them onto the cloud. This way, your integration can read the data from said cloud.

**Comment by Robbe-B** [comment]
@htbuddha, 
Thanks for the clarification ! 
I do agree it's a bit odd that this suddenly stopped working. 
From what I understand from your detailed explanation,  this is definitely the same issue as https://github.com/Robbe-B/maestro_mcz/issues/114.

So therefore I'll close this issue in favour of the other one. 
Any further questions or follow-up can be handled via the other issue.

Personally, I can't do much about this because we need to figure out what the app is doing differently on the older stove models (your model) compared to what the app is doing on the newer models (my model). 

To achieve this, we need to get access to an older stove model. (Which I don't have)
There are obviously a lot of security concerns related to this. But I believe @Crisicus will have a look soon, since some users agreed to share there stove for analysis as described in https://github.com/Robbe-B/maestro_mcz/issues/114.

Kind regards, 
Robbe

**Comment by Robbe-B** [comment]
@htbuddha, 
If you like the work we do, please consider leaving a star on this repo.
Kind regards,
Robbe
