### ISSUE TITLE
Feature Request: Loop Air 8 M1+   - Fan Speed Level 6 = Automatic Fan Level

### ISSUE THREAD

**Issue by VaillantHassIo** [Robbe-B/maestro_mcz#25]
Fan Speed Level 6 mappes to Automatic Fan Level on Loop Air 8 stoves. It would be great to change the List in dropdown and chang eht eumber 6 to A(utomatic) of some kind.

See: https://github.com/Crisicus/maestro_mcz/issues/23#issuecomment-1486282337

**Comment by Crisicus** [comment]
The issue is "auto" is reported as 6 in backend for these types of stoves. We should check if other stoves use actual 6, otherwise a simple switch on the value 6 might do the trick.

**Comment by Robbe-B** [comment]
@Crisicus,
I have some code almost ready to fix this in a proper way. 
As stated in the documentation of Fan entities, the presets cannot be used for controlling the speed.
![image](https://github.com/Robbe-B/maestro_mcz/assets/103053873/07fc2d4c-64fc-49fb-b0e1-3bef331aaa5a)


The reason this is not pushed yet, is because for some reason MCZ removed the "vent 1" from the config. 
Resulting for my stove model in not having the ability anymore to control the 1st fan.

Is this also the case for you ? Can you maybe provide me the diagnostics file (taken with the latest version) ? 

I believe I figured already how to fix this, we should start looking in the config to the sensors defined for the specific mode the stove is currently in.

**Comment by Crisicus** [comment]
My stove is fixed, but currently unplugged as I'm in Japan for travel. I do see Fan 1 however (but unavailable due to it being unplugged). I'll add a diagnostic on 01/10.

**Comment by marrocc** [comment]
Hi. My MCZ MUSA 12 Kw stove has same issue on front Fan. It is present but not available. In attach, the diagnostic.

Thanks for resolution.

[config_entry-maestro_mcz-cd6cb821e13dcd49a5958a69026c2c83.json.txt](https://github.com/Robbe-B/maestro_mcz/files/12793337/config_entry-maestro_mcz-cd6cb821e13dcd49a5958a69026c2c83.json.txt)

**Comment by Robbe-B** [comment]
@marrocc,
Thanks for reporting !

**Comment by lalek54** [comment]
Same problem here. Fan 1 disappeared on a MCZ stream 14. Only fan 2 and fan 3 available. 
I can provide files if you need.
