### ISSUE TITLE
[Regression] Fan Speed changed from Numers to Slider ( percentage )

### ISSUE THREAD

**Issue by VaillantHassIo** [Robbe-B/maestro_mcz#98]
Hi Guys,

i know you put a lot of effort into this and i appreciate your work!

I am not sure why the design for the FAN changed. I am used to select certain speeds eg. 1, 3,5  and now with the slider its only list in percentage which you have to guess or may need to get use to. However since the stove itself present itself with Fan Speed Levels it would make sense - for me at least - to keep the same shema.

Not sure what you think.

Cheers
Mike

**Comment by Robbe-B** [comment]
Hi @VaillantHassIo, 
Unfortunately, this integration is still in a BETA phase and braking changes can be the case from time to time (see readme).
In order to get this integration out of BETA and into the default HACS repo, we need to properly implement functionality as stated in the official documentation.
This change is part of this, it has been done because the official documentation states: 
**"Preset modes should not include named (manual) speed settings as these should be represented as percentages."**
You can check this here => https://developers.home-assistant.io/docs/core/entity/fan

NOTE: 
If you want the old MCZ style of fan speeds back, you can do something like this in your dashboard:
![image](https://github.com/Robbe-B/maestro_mcz/assets/103053873/a36fc2b9-b84d-4c8f-82cc-34d42ff6f26e)

See https://github.com/Robbe-B/maestro_mcz/issues/94#issuecomment-1890939046 for more information

Kind regards,
Robbe
